// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANK0WWDi7f2lgNXKm8w40KnscphSY4GZQ',
    appId: '1:395880072127:web:a0b005ef1796625114d70a',
    messagingSenderId: '395880072127',
    projectId: 'efikasa-77e8a',
    authDomain: 'efikasa-77e8a.firebaseapp.com',
    storageBucket: 'efikasa-77e8a.firebasestorage.app',
    measurementId: 'G-QCFKBE0T0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_zHsW7kmO-cYVFl2Atzi5Tf_aVG6iIs',
    appId: '1:395880072127:android:2b31d83f40e7057914d70a',
    messagingSenderId: '395880072127',
    projectId: 'efikasa-77e8a',
    storageBucket: 'efikasa-77e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCdH_dut3gvNqEILAe7Xq7pS0G2WobAso',
    appId: '1:395880072127:ios:260b3b365d551c5614d70a',
    messagingSenderId: '395880072127',
    projectId: 'efikasa-77e8a',
    storageBucket: 'efikasa-77e8a.firebasestorage.app',
    iosBundleId: 'com.example.efikasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCdH_dut3gvNqEILAe7Xq7pS0G2WobAso',
    appId: '1:395880072127:ios:260b3b365d551c5614d70a',
    messagingSenderId: '395880072127',
    projectId: 'efikasa-77e8a',
    storageBucket: 'efikasa-77e8a.firebasestorage.app',
    iosBundleId: 'com.example.efikasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANK0WWDi7f2lgNXKm8w40KnscphSY4GZQ',
    appId: '1:395880072127:web:3cfa19d60294189214d70a',
    messagingSenderId: '395880072127',
    projectId: 'efikasa-77e8a',
    authDomain: 'efikasa-77e8a.firebaseapp.com',
    storageBucket: 'efikasa-77e8a.firebasestorage.app',
    measurementId: 'G-DNHPN07L6G',
  );
}
